<a href="https://colab.research.google.com/github/min03027/start/blob/main/DL_Perceptron_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 문제1. 단일층 퍼셉트론 구현
요구사항
- 입력데이터는 3차원 벡터
- 가중치와 바이어스는 임의로 초기화
- 활성화 함수는 시그모이드 사용
- 입력 데이터에 대한 출력을 계산

In [ ]:
import numpy as np

# 함수선언
def sigmoid(x):
  return 1/(1+np.exp(-x))

# 데이터 입력
inputs = np.array([1,2,3])

#가중치와 편향을 임의로 초기화
np.random.seed(42)
weights = np.random.rand(3)
bias = np.random.rand(1)

# 입력데이터에 대한 출력을 계산
output = sigmoid(np.dot(inputs,weights)+bias)

#결과 출력
print("perceptron output : ",output)

perceptron output :  [0.99376058]


# 문제2. 다중 퍼셉트론과 순전파 구현

요구사항
- 입력데이터는 4차원 벡터
- 첫번째 은닉층은 5개의 노드를, 두번째 은닉층은 3개의 노드를 가진다.
- 가중치와 바이어스는 임의로 초기화
- 활성화 함수는 시그모이드 사용
- 입력 데이터에 대한 출력을 계산

In [ ]:
import numpy as np

# 활성화함수 정의
def sigmoid (x):
  return 1/(1+np.exp(-x))

# 입력데이터
inputs = ([1,2,3,4])

# 가중치와 편향 정의
np.random.seed(42)
weights_input_hidden1 = np.random.rand(4,5)
bias_hidden1 = np.random.rand(1,5)
weights_hidden1_hidden2 = np.random.rand(5,3)
bias_hidden2 = np.random.rand(1,3)
weights_hidden2_output= np.random.rand(3,1)
bias_output = np.random.rand(1,1)

#순전파
hidden_layer_activation = np.dot(inputs,weights_input_hidden1)+bias_hidden1
hidden_layer1_output = sigmoid(hidden_layer_activation)
hidden_layer2_activation = np.dot(hidden_layer1_output,weights_hidden1_hidden2)+bias_hidden2
hidden_layer2_output = sigmoid(hidden_layer2_activation)
final_input= np.dot(hidden_layer2_output,weights_hidden2_output)+bias_output
final_output = sigmoid(final_input)

#프린트
print("final predicted", final_output)


final predicted [[0.88265813]]


# 문제3. 역전파를 이용한 신경망 학습
1. 다층 퍼셉트론에서의 오차계산
2. 역전파 알고리즘을 통해 가중치와 편향 계산


요구사항
- 입력데이터는 2차원 벡터
- 첫번째 은닉층은 4개의 노드를, 출력층은 1개의 노드를 가진다.
- 가중치와 바이어스는 임의로 초기화
- 활성화 함수는 시그모이드 사용
- 주어진 출력 데이터의 오차 계산, 역전파 알고리즘을 통한 가중치와 편향 계산
- 학습률을 0.1로 설정

In [ ]:
import numpy as np

def sigmoid(x):
  return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
  return sigmoid(x)*(1-sigmoid(x))

inputs = np.array([[1,2]])
actual_output = np.array([[1]])

np.random.seed(42)
weights_input = np.random.rand(2,4)
bias_input = np.random.rand(1,4)
weights_hidden1 = np.random.rand(4,1)
bias_hidden1 = np.random.rand(1,1)

# 순전파
input_activation = np.dot(inputs,weights_input)+bias_input
input_result = sigmoid(input_activation)
hidden1_activation = np.dot(input_result,weights_hidden1)+bias_hidden1
hidden1_result = sigmoid(hidden1_activation)

#오차비교
error = actual_output- hidden1_result
d_predicted_output = error*sigmoid_derivative(hidden1_activation)
error_hidden_layer = d_predicted_output.dot(hidden1_result.T)
d_hidden_layer = error_hidden_layer*sigmoid_derivative(hidden1_activation)

# 가중치와 편향 업데이트
learning_rate = 0.1
weights_hidden1 += input_result.T.dot(d_predicted_output)*learning_rate
bias_hidden1 += np.sum(d_predicted_output,axis=0,keepdims =True)*learning_rate
weights_input +=inputs.T.dot(d_hidden_layer)*learning_rate
bias_input +=np.sum(d_hidden_layer,axis=0,keepdims=True)*learning_rate

print("updated weights from input to hidden layer : ",weights_input)
print("Updated bias of hidden layer:\n", bias_input)
print("Updated weights from hidden to output layer:\n", weights_hidden1)
print("Updated bias of output layer:\n", bias_hidden1)




updated weights from input to hidden layer :  [[0.37490598 0.95108017 0.73235981 0.59902435]
 [0.15675037 0.15672625 0.05881534 0.86690788]]
Updated bias of hidden layer:
 [[0.60148088 0.70843844 0.02095036 0.97027572]]
Updated weights from hidden to output layer:
 [[0.83474094]
 [0.21491288]
 [0.18389081]
 [0.18623271]]
Updated bias of output layer:
 [[0.30717466]]


# 문제4. 간단한 2층 신경망의 오차역전파법 구현
1. 입력데이터 [1,0][1,0][1,0]
2. 실제 출력값 [1][1][1]


요구사항
- 입력데이터는 2개의 노드
- 첫번째 은닉층은 2개의 노드
- 출력층은 1개의 노드
- 가중치와 바이어스는 임의로 초기화
- 활성화 함수는 시그모이드 사용
- 주어진 출력 데이터의 오차 계산, 역전파 알고리즘을 통한 가중치와 편향 계산
- 학습률을 0.1로 설정




In [41]:
# 작성코드
import numpy as np

#함수정의
def sigmoid(x):
  return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
  return sigmoid(x)*(1-sigmoid(x))

#입력
input= np.array([[1,0],[1,0],[1,0]])
actual_output = np.array([[1],[1],[1]])

# 가중치와 편향
np.random.seed(42)
weights_input = np.random.rand(2,2)
bias_input = np.random.rand(1,2)
weights_hidden1 = np.random.rand(2,1)
bias_hidden1 = np.random.rand(1,1)
weights_output = np.random.rand(1,1)
bias_output = np.random.rand(1,1)

#순전파
input_activation = np.dot(input,weights_input)+bias_input
input_result = sigmoid(input_activation)
hidden_activation = np.dot(input_result,weights_hidden1)+bias_hidden1
hidden_result = sigmoid(hidden_activation)
output_activtion = np.dot(hidden_result,weights_output)+bias_output
output_result = sigmoid(output_activtion)

#오차계산
error = actual_output - output_result
d_predicted_output = error * sigmoid_derivative(output_result)
error_hidden = d_predicted_output.dot(weights_output.T)
d_hidden = error_hidden * sigmoid_derivative(hidden_result)

#가중치와 편향 업데이트
learning_rate = 0.1
weights_output += hidden_result.T.dot(d_predicted_output) * learning_rate
bias_output += np.sum(d_predicted_output, axis=0, keepdims=True) * learning_rate
weights_hidden1 += input_result.T.dot(d_hidden) * learning_rate
bias_hidden1 += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate
weights_input += input.T.dot(d_hidden.dot(weights_hidden1.T)) * learning_rate
bias_input += np.sum(d_hidden.dot(weights_hidden1.T) * sigmoid_derivative(input_result), axis=0, keepdims=True) * learning_rate



print("Updated weights from input to first hidden layer:", weights_input)
print("Updated bias of first hidden layer:", bias_input)
print("Updated weights from first hidden layer to second hidden layer:", weights_hidden1)
print("Updated bias of second hidden layer:", bias_hidden1)
print("Updated weights from second hidden layer to output layer:", weights_output)
print("Updated bias of output layer:", bias_output)

Updated weights from input to first hidden layer: [[0.37476487 0.95394641]
 [0.73199394 0.59865848]]
Updated bias of first hidden layer: [[0.15606961 0.1566984 ]]
Updated weights from first hidden layer to second hidden layer: [[0.06042543]
 [0.86897138]]
Updated bias of second hidden layer: [[0.60483447]]
Updated weights from second hidden layer to output layer: [[0.72720679]]
Updated bias of output layer: [[0.04499302]]


In [42]:
# 수정코드
import numpy as np

# 함수 정의
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

# 입력
input_data = np.array([[1, 0], [1, 0], [1, 0]])
actual_output = np.array([[1], [1], [1]])

# 가중치와 편향 초기화
np.random.seed(42)
weights_input = np.random.rand(2, 2)
bias_input = np.random.rand(1, 2)
weights_hidden1 = np.random.rand(2, 1)
bias_hidden1 = np.random.rand(1, 1)
weights_output = np.random.rand(1, 1)
bias_output = np.random.rand(1, 1)

# 순전파
input_activation = np.dot(input_data, weights_input) + bias_input
input_result = sigmoid(input_activation)
hidden_activation = np.dot(input_result, weights_hidden1) + bias_hidden1
hidden_result = sigmoid(hidden_activation)
output_activation = np.dot(hidden_result, weights_output) + bias_output
output_result = sigmoid(output_activation)

# 오차 계산
error = actual_output - output_result
d_predicted_output = error * sigmoid_derivative(output_result)
error_hidden = d_predicted_output.dot(weights_output.T)
d_hidden = error_hidden * sigmoid_derivative(hidden_result)

# 가중치와 편향 업데이트
learning_rate = 0.1

# Output layer
weights_output += hidden_result.T.dot(d_predicted_output) * learning_rate
bias_output += np.sum(d_predicted_output, axis=0, keepdims=True) * learning_rate

# Hidden layer
weights_hidden1 += input_result.T.dot(d_hidden) * learning_rate
bias_hidden1 += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate

# Input layer
weights_input += input_data.T.dot(d_hidden.dot(weights_hidden1.T) * sigmoid_derivative(input_result)) * learning_rate
bias_input += np.sum(d_hidden.dot(weights_hidden1.T) * sigmoid_derivative(input_result), axis=0, keepdims=True) * learning_rate

print("Updated weights from input to first hidden layer:", weights_input)
print("Updated bias of first hidden layer:", bias_input)
print("Updated weights from first hidden layer to output layer:", weights_hidden1)
print("Updated bias of hidden layer:", bias_hidden1)
print("Updated weights from hidden layer to output layer:", weights_output)
print("Updated bias of output layer:", bias_output)


Updated weights from input to first hidden layer: [[0.37459109 0.95141818]
 [0.73199394 0.59865848]]
Updated bias of first hidden layer: [[0.15606961 0.1566984 ]]
Updated weights from first hidden layer to output layer: [[0.06042543]
 [0.86897138]]
Updated bias of hidden layer: [[0.60483447]]
Updated weights from hidden layer to output layer: [[0.72720679]]
Updated bias of output layer: [[0.04499302]]


In [43]:
# 다른방식
import numpy as np

# 함수 정의
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

x = np.array([[1,0],[1,0],[1,0]])
y = np.array([[1],[1],[1]])


np.random.seed(42)
w1 = np.random.rand(2,2)
b1 = np.random.rand(1,2)
w2 = np.random.rand(2,1)
b2 = np.random.rand(1,1)


hidden_acti= np.dot(x,w1) + b1 # 활성화
hidden_output = sigmoid(hidden_acti)
output_acti = np.dot(hidden_output,w2) + b2
output_output = sigmoid(output_acti)

error = y - output_output
d_predicted_output = error * sigmoid_derivative(output_acti)

error_hidden_layer = d_predicted_output.dot(w2.T)
d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_acti)

learning_rate = 0.1
w2 += hidden_output.T.dot(d_predicted_output) * learning_rate
b2 += np.sum(d_predicted_output, axis = 0, keepdims = True) * learning_rate
w1 += x.T.dot(d_hidden_layer) * learning_rate
b1 += np.sum(d_hidden_layer, axis = 0, keepdims = True) * learning_rate

print("Updated weights from input to hidden layer :\n", w1)
print("Updated bias of hidden layer 1:\n", b1)
print("Updated weights from hidden layer to output layer:\n", w2)
print("Updated bias of output layer :\n", b2)

Updated weights from input to hidden layer :
 [[0.37468886 0.95249047]
 [0.73199394 0.59865848]]
Updated bias of hidden layer 1:
 [[0.15616738 0.15777068]]
Updated weights from hidden layer to output layer:
 [[0.06499735]
 [0.87442848]]
Updated bias of output layer :
 [[0.61209594]]


# 문제5. 3층 신경망의 오차역전파법 구현
1. 입력데이터 [0.5,0.1,0.2][0.5,0.1,0.2][0.5,0.1,0.2]
2. 실제 출력값 [0.7,0.3][0.7,0.3][0.7,0.3]


요구사항
- 입력데이터는 3개의 노드
- 첫번째 은닉층은 4개의 노드
- 두번째 은닉층은 3개의 노드
- 출력층은 2개의 노드
- 가중치와 바이어스는 임의로 초기화
- 활성화 함수는 시그모이드 사용
- 주어진 출력 데이터의 오차 계산, 역전파 알고리즘을 통한 가중치와 편향 계산
- 학습률을 0.1로 설정


In [47]:
import numpy as np

# 함수 정의
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

x = np.array([[0.5,0.1,0.2],[0.5,0.1,0.2],[0.5,0.1,0.2]])
y = np.array([[0.7,0.3],[0.7,0.3],[0.7,0.3]])


np.random.seed(42)
w1 = np.random.rand(3,4)
b1 = np.random.rand(1,4)
w2 = np.random.rand(4,3)
b2 = np.random.rand(1,3)
w3 = np.random.rand(3,2)
b3 = np.random.rand(1,2)

hidden_acti= np.dot(x,w1) + b1 # 활성화
hidden_output = sigmoid(hidden_acti)
hidden2_acti = np.dot(hidden_output,w2) + b2
hidden2_output = sigmoid(hidden2_acti)
output_acti = np.dot(hidden2_output,w3) + b3
output_output = sigmoid(output_acti)

#오차계산
error = y - output_output
d_predicted_output = error * sigmoid_derivative(output_acti)

error_hidden2 = d_predicted_output.dot(w3.T)
d_hidden2 = error_hidden2 * sigmoid_derivative(hidden2_acti)

error_hidden1 = d_hidden2.dot(w2.T)
d_hidden1 = error_hidden1 * sigmoid_derivative(hidden_acti)


learning_rate = 0.1
w3 += hidden2_output.T.dot(d_predicted_output) * learning_rate
b3 += np.sum(d_predicted_output, axis = 0, keepdims = True) * learning_rate
w2 += hidden_output.T.dot(d_hidden2) * learning_rate
b2 += np.sum(d_hidden2, axis = 0, keepdims = True) * learning_rate
w1 += x.T.dot(d_hidden1) * learning_rate
b1 += np.sum(d_hidden1, axis = 0, keepdims = True) * learning_rate

print("Updated weights from input to hidden layer 1:\n", w1)
print("Updated bias of hidden layer 1:\n", b1)
print("Updated weights from hidden layer 1 to hidden layer 2:\n", w2)
print("Updated bias of hidden layer 2:\n", b2)
print("Updated weights from hidden layer 2 to output layer:\n", w3)
print("Updated bias of output layer:\n", b3)

Updated weights from input to hidden layer 1:
 [[0.37426242 0.95039822 0.73171876 0.59845621]
 [0.1559631  0.1559313  0.05802858 0.86613569]
 [0.60100393 0.70794614 0.02047442 0.96982894]]
Updated bias of hidden layer 1:
 [[0.83188724 0.21170695 0.18127461 0.18299995]]
Updated weights from hidden layer 1 to hidden layer 2:
 [[0.30401908 0.52137663 0.43083896]
 [0.29102388 0.60874429 0.13847655]
 [0.29195804 0.36353573 0.45514513]
 [0.78497582 0.19664259 0.51324247]]
Updated bias of hidden layer 2:
 [[0.59212113 0.04200636 0.60609051]]
Updated weights from hidden layer 2 to output layer:
 [[0.16571334 0.04722376]
 [0.9445027  0.94939008]
 [0.80364104 0.28698781]]
Updated bias of output layer:
 [[0.09202438 0.6633036 ]]


# 문제6. 다중클래스 분류를 위한 3층 신경망의 오차역전파법 구현
1. 입력데이터 [0.2,0.4,0.6,0.8][0.2,0.4,0.6,0.8][0.2,0.4,0.6,0.8]
2. 실제 출력값 [0,1,0][0,1,0][0,1,0]


요구사항
- 입력데이터는 4개의 노드
- 첫번째 은닉층은 5개의 노드
- 두번째 은닉층은 4개의 노드
- 출력층은 3개의 노드 / 소프트맥스 활성화 함수
- 가중치와 바이어스는 임의로 초기화
- 활성화 함수는 시그모이드 사용(출력층 제외)
- 주어진 출력 데이터을 이용한 (원-핫인코딩)을 토한 오차계산
- 오차 역전파법을 통한 가중치와 편향 계산
- 학습률을 0.1로 설정


In [52]:
import numpy as np

# 함수 정의
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

def softmax(x):
    e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e_x / e_x.sum(axis=-1, keepdims=True)

def cross_entropy_loss(y_true, y_pred):
    # 크로스 엔트로피 손실 함수
    return -np.sum(y_true * np.log(y_pred + 1e-10), axis=-1)

def softmax_derivative(y_true, y_pred):
    # 소프트맥스 함수와 크로스 엔트로피 손실 함수의 결합된 미분
    return y_pred - y_true


x = np.array([[0.2,0.4,0.6,0.8],[0.2,0.4,0.6,0.8],[0.2,0.4,0.6,0.8]])
y = np.array([[0,1,0],[0,1,0],[0,1,0]])


np.random.seed(42)
w1 = np.random.rand(4,5)
b1 = np.random.rand(1,5)
w2 = np.random.rand(5,4)
b2 = np.random.rand(1,4)
w3 = np.random.rand(4,3)
b3 = np.random.rand(1,3)

hidden_acti= np.dot(x,w1) + b1 # 활성화
hidden_output = sigmoid(hidden_acti)
hidden2_acti = np.dot(hidden_output,w2) + b2
hidden2_output = sigmoid(hidden2_acti)
output_acti = np.dot(hidden2_output,w3) + b3
output_output = softmax(output_acti)

#오차계산
error = softmax_derivative(y, output_output)  # 수정된 부분
d_predicted_output = error

error_hidden2 = d_predicted_output.dot(w3.T)
d_hidden2 = error_hidden2 * sigmoid_derivative(hidden2_acti)

error_hidden1 = d_hidden2.dot(w2.T)
d_hidden1 = error_hidden1 * sigmoid_derivative(hidden_acti)


learning_rate = 0.1
w3 += hidden2_output.T.dot(d_predicted_output) * learning_rate
b3 += np.sum(d_predicted_output, axis = 0, keepdims = True) * learning_rate
w2 += hidden_output.T.dot(d_hidden2) * learning_rate
b2 += np.sum(d_hidden2, axis = 0, keepdims = True) * learning_rate
w1 += x.T.dot(d_hidden1) * learning_rate
b1 += np.sum(d_hidden1, axis = 0, keepdims = True) * learning_rate

print("Updated weights from input to hidden layer 1:\n", w1)
print("Updated bias of hidden layer 1:\n", b1)
print("Updated weights from hidden layer 1 to hidden layer 2:\n", w2)
print("Updated bias of hidden layer 2:\n", b2)
print("Updated weights from hidden layer 2 to output layer:\n", w3)
print("Updated bias of output layer:\n", b3)

Updated weights from input to hidden layer 1:
 [[0.37439102 0.95069311 0.73189755 0.59865879 0.15603834]
 [0.15569632 0.05804122 0.86598336 0.60111562 0.70811197]
 [0.0201372  0.96984626 0.83215346 0.21234003 0.18188405]
 [0.18280811 0.30415745 0.52437085 0.43194624 0.29130792]]
Updated bias of hidden layer 1:
 [[0.6111074  0.13938787 0.29166268 0.36636337 0.45616846]]
Updated weights from hidden layer 1 to hidden layer 2:
 [[0.78151649 0.19862287 0.51717238 0.59068959]
 [0.04252398 0.60641728 0.17367639 0.06320078]
 [0.94454076 0.96438432 0.81188547 0.30256576]
 [0.09372612 0.68309984 0.44332046 0.1201782 ]
 [0.49131218 0.03327867 0.91242313 0.25695825]]
Updated bias of hidden layer 2:
 [[0.65738718 0.3102364  0.52419064 0.54428973]]
Updated weights from hidden layer 2 to output layer:
 [[ 0.25553788  0.83339001  0.84064402]
 [ 1.00889074  0.76112147  0.66221406]
 [ 0.99360384 -0.04971792  0.26246368]
 [ 0.10844598  0.20351894  0.44726998]]
Updated bias of output layer:
 [[0.34778734 